language: node_js
node_js:
  - v12.14.1

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves fpr cypress tests
      - libgconf-2-4

before_install:
  - echo do pre-install things here...

install:
  - node --version
  - pwd
  - npm install

before_script:
  - echo do pre-scripts things here...

script:
  ## Run unit tests
  # - npm run test-once

  ## Runs e2e cypress + cucmber tests
  # - npm start & wait-on http://localhost:8000
  # - npm run e2e-headless

   - npm test

  # - do your other automated tests here!


after_script:
  - echo ran script
after_success:

  - if [ "$TRAVIS_PULL_REQUEST" = true ]; then
        echo "not deploying, it's just a pull request build!";
        echo TRAVIS_PULL_REQUEST_BRANCH - $TRAVIS_PULL_REQUEST_BRANCH;
        echo TRAVIS_PULL_REQUEST - $TRAVIS_PULL_REQUEST;
        echo TRAVIS_BRANCH - $TRAVIS_BRANCH;
        exit 0;
      fi;

  - if [ "$TRAVIS_BRANCH" = dev ]; then
        echo TRAVIS_PULL_REQUEST_BRANCH - $TRAVIS_PULL_REQUEST_BRANCH;
        echo TRAVIS_PULL_REQUEST - $TRAVIS_PULL_REQUEST;
        echo TRAVIS_BRANCH - $TRAVIS_BRANCH;
        echo "It's a push or PR to dev! Let's deploy to the dev environment!";
        exit 0;     
      fi;
      
  - if [ "$TRAVIS_BRANCH" = staging ]; then
        echo TRAVIS_PULL_REQUEST_BRANCH - $TRAVIS_PULL_REQUEST_BRANCH;
        echo TRAVIS_PULL_REQUEST - $TRAVIS_PULL_REQUEST;
        echo TRAVIS_BRANCH - $TRAVIS_BRANCH;
        echo "It's a push or PR to staging! Let's deploy to the staging environment!";
        exit 0;     
      fi;

  - if [ "$TRAVIS_BRANCH" = master ]; then
        echo TRAVIS_PULL_REQUEST_BRANCH - $TRAVIS_PULL_REQUEST_BRANCH;
        echo TRAVIS_PULL_REQUEST - $TRAVIS_PULL_REQUEST;
        echo TRAVIS_BRANCH - $TRAVIS_BRANCH;
        echo "It's a push or PR to master! Let's deploy to the master environment!";
        exit 0;     
      fi;

      

  # - do your deploy commands here!
  - echo Welp, that's another happy CI deploy!
  - echo "this is the branch $TRAVIS_BRANCH"

  

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: public
#   edge: true
#   on:
#     branch: v1.0.1-release

matrix:
  fast_finish: true

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
